// Generated by gencpp from file stag_ros/STagMarkerArray.msg
// DO NOT EDIT!


#ifndef STAG_ROS_MESSAGE_STAGMARKERARRAY_H
#define STAG_ROS_MESSAGE_STAGMARKERARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <stag_ros/STagMarker.h>

namespace stag_ros
{
template <class ContainerAllocator>
struct STagMarkerArray_
{
  typedef STagMarkerArray_<ContainerAllocator> Type;

  STagMarkerArray_()
    : stag_array()  {
    }
  STagMarkerArray_(const ContainerAllocator& _alloc)
    : stag_array(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::stag_ros::STagMarker_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::stag_ros::STagMarker_<ContainerAllocator> >::other >  _stag_array_type;
  _stag_array_type stag_array;





  typedef boost::shared_ptr< ::stag_ros::STagMarkerArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stag_ros::STagMarkerArray_<ContainerAllocator> const> ConstPtr;

}; // struct STagMarkerArray_

typedef ::stag_ros::STagMarkerArray_<std::allocator<void> > STagMarkerArray;

typedef boost::shared_ptr< ::stag_ros::STagMarkerArray > STagMarkerArrayPtr;
typedef boost::shared_ptr< ::stag_ros::STagMarkerArray const> STagMarkerArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stag_ros::STagMarkerArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stag_ros::STagMarkerArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stag_ros::STagMarkerArray_<ContainerAllocator1> & lhs, const ::stag_ros::STagMarkerArray_<ContainerAllocator2> & rhs)
{
  return lhs.stag_array == rhs.stag_array;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stag_ros::STagMarkerArray_<ContainerAllocator1> & lhs, const ::stag_ros::STagMarkerArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stag_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::stag_ros::STagMarkerArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stag_ros::STagMarkerArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stag_ros::STagMarkerArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stag_ros::STagMarkerArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stag_ros::STagMarkerArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stag_ros::STagMarkerArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stag_ros::STagMarkerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a27e36452f4864fc82763841a00f252";
  }

  static const char* value(const ::stag_ros::STagMarkerArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a27e36452f4864fULL;
  static const uint64_t static_value2 = 0xc82763841a00f252ULL;
};

template<class ContainerAllocator>
struct DataType< ::stag_ros::STagMarkerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stag_ros/STagMarkerArray";
  }

  static const char* value(const ::stag_ros::STagMarkerArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stag_ros::STagMarkerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stag_ros/STagMarker[] stag_array\n"
"================================================================================\n"
"MSG: stag_ros/STagMarker\n"
"std_msgs/Header header\n"
"std_msgs/Int32 id \n"
"geometry_msgs/Pose pose\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int32\n"
"int32 data\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::stag_ros::STagMarkerArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stag_ros::STagMarkerArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stag_array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct STagMarkerArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stag_ros::STagMarkerArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stag_ros::STagMarkerArray_<ContainerAllocator>& v)
  {
    s << indent << "stag_array[]" << std::endl;
    for (size_t i = 0; i < v.stag_array.size(); ++i)
    {
      s << indent << "  stag_array[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::stag_ros::STagMarker_<ContainerAllocator> >::stream(s, indent + "    ", v.stag_array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // STAG_ROS_MESSAGE_STAGMARKERARRAY_H
